### ISSUE TITLE
The insight of "out-of-range behavior"

### ISSUE THREAD

**Issue by kwea123** [vsitzmann/siren#8]
What exactly is the insight of studying the "out-of-range behaviour" in the notebook?
The signal is not repeated on this range of (-50, 50), so...?
In my opinion, I would study if the model can generalize to something larger than [-1, 1], for example if it can do some reasonable "out-painting" off the image borders, however it doesn't, as shown in the image.
![a](https://user-images.githubusercontent.com/11364490/86324998-5b2e1480-bc7a-11ea-9fd1-3fc334e05486.png)

Do you think it is possible with some tweak to the network? Otherwise I don't really understand why showing this block.

**Comment by vsitzmann** [comment]
The reason why this is interesting is because one could assume that periodic nonlinearities mean that the function represented by SIREN is itself somehow periodic - and in fact, it very well may be, just with a period that is very, very large. This is just a little investigation into that question, which many people had voiced curiosity about.
